# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed95701dae802916ff7f1ebeabfe2165275f1c2c4d1b33b5ff2cf9cf130583115fb7cde7e0cfef27a00693270b6eaec639190de16ab4a2428b986e7d3f001ad1

test:
  secret_key_base: 920f51cda1fe55f15e46a0955a212c48312fc29beb216bfdeeb5aa0d7651fe0cb7565b92beda07919a1867180032996ec07e04afc65e0e1480fac0d267798dc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
